# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0002_auto_20190804_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
