# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0003_auto_20190804_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
