# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0004_remove_review_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creativity',
        ),
    ]
