# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0005_remove_project_creativity'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
